using UnityEngine;

/// <summary>
/// Data structure containing information about a player action that generates sound/noise.
/// This is created when the player performs an action (e.g., hitting an object with an item).
/// The action's properties (intensity, duration, frequency) come from the object/item used.
/// </summary>
public struct PlayerActionData
{
    /// <summary>
    /// Position where the action occurred (usually player position or interaction point)
    /// </summary>
    public Vector3 position;

    /// <summary>
    /// Intensity of the sound generated by this action (from the object/item)
    /// </summary>
    public float intensity;

    /// <summary>
    /// Duration of the sound generated by this action (from the object/item)
    /// </summary>
    public float duration;

    /// <summary>
    /// Frequency of the sound generated by this action (from the object/item)
    /// Low = 0, Mid = 1, High = 2
    /// </summary>
    public float frequency;

    /// <summary>
    /// Radius of the sound generated by this action (from the object/item)
    /// </summary>
    public float radius;

    public PlayerActionData(Vector3 pos, SoundEmissionData soundSource)
    {
        switch (soundSource.SoundClass.Frequency)
        {
            case Frequency.Low: frequency = 0f; break;
            case Frequency.Mid: frequency = 1f; break;
            case Frequency.High: frequency = 2f; break;
            default: frequency = 1f; break;
        }
        position = pos;
        intensity = soundSource.Intensity;
        duration = soundSource.Duration;
        radius = soundSource.Radius;
    }
}

